apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tiny-vnf.fullname" . }}
  namespace: {{ template "tiny-vnf.namespace" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  index.html: <!DOCTYPE html> <html> <body> <h1>Welcome to {{ .Release.Name }} application!</h1> </body></html>
