{{- if or .Values.headlessService (and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "statefulset"))}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tiny-vnf.fullname" . }}-headless
  namespace: {{ template "tiny-vnf.namespace" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "tiny-vnf.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
{{- end }}

