{{- if .Values.secondaryNet.enabled -}}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-tiny-vnf
  namespace: {{ template "tiny-vnf.namespace" . }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": {{ .Values.secondaryNet.type | quote }},
      "mode": "private",
      "master": {{ .Values.secondaryNet.master | quote }},
      "ipam": {
        "type": {{ .Values.secondaryNet.ipamType | quote }},
        "subnet": {{ .Values.secondaryNet.subnet | quote }},
        "rangeStart": {{ .Values.secondaryNet.rangeStart | quote }},
        "rangeEnd": {{ .Values.secondaryNet.rangeEnd | quote }},
        "gateway": {{ .Values.secondaryNet.gateway | quote }}
      }
    }'
{{- end }}
