apiVersion: {{ template "tiny-vnf.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "tiny-vnf.fullname" . }}
  namespace: {{ template "tiny-vnf.namespace" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "tiny-vnf.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "tiny-vnf.serviceAccountName" . }}
  namespace: {{ template "tiny-vnf.namespace" . }}

