apiVersion: {{ template "tiny-vnf.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "tiny-vnf.fullname" . }}
  namespace: {{ template "tiny-vnf.namespace" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
