{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiny-vnf.fullname" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tiny-vnf.selectorLabels" . | nindent 4 }}
{{ end }}
