{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tiny-vnf.serviceAccountName" . }}
  namespace: {{ template "tiny-vnf.namespace" .  }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
