{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "statefulset")}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tiny-vnf.fullname" . }}
  namespace: {{ template "tiny-vnf.namespace" . }}
  labels:
    {{- include "tiny-vnf.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tiny-vnf.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "tiny-vnf.fullname" . }}-headless
  template:
    metadata:
    {{- if .Values.secondaryNet.enabled }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ include "tiny-vnf.fullname" . }}-nad
    {{- end }}
      labels:
        {{- include "tiny-vnf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiny-vnf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: pvc-tiny
            mountPath: "/tmp/pvc"
          - name: config
            mountPath: "/var/www"
          - name: secret
            mountPath: "/tmp/secret"
      volumes:
      - name: pvc-tiny
        persistentVolumeClaim:
          claimName: {{ tpl (.Values.persistence.existingClaim | default (include "tiny-vnf.fullname" .)) . }}
      - name: config
        configMap:
          name: {{ template "tiny-vnf.fullname" . }}
      - name: secret
        secret:
          secretName: {{ template "tiny-vnf.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: pvc-tiny
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- with .Values.persistence.selectorLabels }}
      selector:
        matchLabels:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- end }}
